project(${PACKAGE_NAME})

file(GLOB HEADERS_ "*.h")

add_library(${PROJECT_NAME} INTERFACE)
add_library(${PACKAGE_NAME}::${PROJECT_NAME} ALIAS ${PROJECT_NAME})

target_include_directories(${PROJECT_NAME} INTERFACE
	$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/..>
	$<INSTALL_INTERFACE:include/${PACKAGE_NAME}>)
	
set_target_properties(
	${PROJECT_NAME}
	PROPERTIES
		PUBLIC_HEADER "${HEADERS_}")

install(
	DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	DESTINATION include/${PACKAGE_NAME}/${PROJECT_NAME}
	FILES_MATCHING
		PATTERN "*.h"
		PATTERN "*.natvis")
install(
	TARGETS ${PROJECT_NAME}
	EXPORT ${PACKAGE_NAME}Config
	INCLUDES DESTINATION include/${PACKAGE_NAME}
	PUBLIC_HEADER DESTINATION include/${PACKAGE_NAME}/${PROJECT_NAME})