#ifndef ADAPT_UTILITY_MACROS_H
#define ADAPT_UTILITY_MACROS_H

#define ADAPT_TIE_ARGS(...) __VA_ARGS__


//----------汎用マクロ----------

#define ADAPT_CONCAT_IMPL(X, Y) X##Y
#define ADAPT_CONCAT(X,Y) ADAPT_CONCAT_IMPL(X, Y)

#define ADAPT_EXPAND_VARS(MACRO, ARGS) MACRO ARGS//msvcでのバグ回避のためのマクロ

#define ADAPT_DETAIL_NUM_ARGS_2(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, N, ...) N
#define ADAPT_DETAIL_NUM_ARGS_1(...) ADAPT_EXPAND_VARS(ADAPT_DETAIL_NUM_ARGS_2, (__VA_ARGS__))
#define ADAPT_GET_NUM_ARGS(...) ADAPT_DETAIL_NUM_ARGS_1(__VA_ARGS__, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

#define ADAPT_DETAIL_SELECT_MACRO_NUM(MACRO, CONV, ...) ADAPT_EXPAND_VARS(ADAPT_CONCAT, (MACRO, ADAPT_GET_NUM_ARGS(__VA_ARGS__)))(CONV, __VA_ARGS__)

//MSVCとclang/gccで記述統一ができなかった。
#ifdef _MSC_VER

//コンマ版
#define ADAPT_DETAIL_EXPAND_CONV_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_2(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_3(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_4(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_5(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_6(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_7(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_8(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_9(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_10(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_11(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_12(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_13(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_14(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_15(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_16(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_17(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_18(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_19(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_20(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_21(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_22(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_23(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_24(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_25(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_26(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_27(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_28(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_29(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_30(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_31(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_32(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_31, (CONV, __VA_ARGS__))

//セミコロン版
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_32(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31, (CONV, __VA_ARGS__))

#else

//コンマ版
#define ADAPT_DETAIL_EXPAND_CONV_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_2(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_3(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_4(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_5(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_6(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_7(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_8(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_9(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_10(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_11(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_12(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_13(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_14(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_15(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_16(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_17(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_18(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_19(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_20(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_21(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_22(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_23(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_24(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_25(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_26(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_27(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_28(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_29(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_30(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_31(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_32(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_31(CONV, __VA_ARGS__)

//セミコロン版
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_32(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, __VA_ARGS__)

#endif


#define ADAPT_DETAIL_EXPAND_CONV(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM(ADAPT_DETAIL_EXPAND_CONV_, CONV, __VA_ARGS__)

#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_, CONV, __VA_ARGS__)


#endif