#ifndef ADAPT_UTILITY_MACROS_H
#define ADAPT_UTILITY_MACROS_H

#define ADAPT_TIE_ARGS(...) __VA_ARGS__


//----------汎用マクロ----------

#define ADAPT_CONCAT_IMPL(X, Y) X##Y
#define ADAPT_CONCAT(X,Y) ADAPT_CONCAT_IMPL(X, Y)

#define ADAPT_EXPAND_VARS(MACRO, ARGS) MACRO ARGS//msvcでのバグ回避のためのマクロ

#define ADAPT_DETAIL_NUM_ARGS_2( _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, _10, _11, _12, _13, _14, _15, _16,\
								_17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, N, ...) N
#define ADAPT_DETAIL_NUM_ARGS_1(...) ADAPT_EXPAND_VARS(ADAPT_DETAIL_NUM_ARGS_2, (__VA_ARGS__))
#define ADAPT_GET_NUM_ARGS(...) ADAPT_DETAIL_NUM_ARGS_1(__VA_ARGS__, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

#define ADAPT_DETAIL_SELECT_MACRO_NUM(MACRO, CONV, ...) ADAPT_EXPAND_VARS(ADAPT_CONCAT, (MACRO, ADAPT_GET_NUM_ARGS(__VA_ARGS__)))(CONV, __VA_ARGS__)

#define ADAPT_DETAIL_NUM_ARGS_PAIR_2( _1a,  _1b,  _2a,  _2b,  _3a,  _3b,  _4a,  _4b,  _5a,  _5b,  _6a,  _6b,  _7a,  _7b,  _8a,  _8b,\
									  _9a,  _9b, _10a, _10b, _11a, _11b, _12a, _12b, _13a, _13b, _14a, _14b, _15a, _15b, _16a, _16b,\
									 _17a, _17b, _18a, _18b, _19a, _19b, _20a, _20b, _21a, _21b, _22a, _22b, _23a, _23b, _24a, _24b,\
									 _25a, _25b, _26a, _26b, _27a, _27b, _28a, _28b, _29a, _29b, _30a, _30b, _31a, _31b, _32a, _32b, N, ...) N
#define ADAPT_DETAIL_NUM_ARGS_PAIR_1(...) ADAPT_EXPAND_VARS(ADAPT_DETAIL_NUM_ARGS_PAIR_2, (__VA_ARGS__))
#define ADAPT_GET_NUM_ARGS_PAIR(...) ADAPT_DETAIL_NUM_ARGS_PAIR_1(__VA_ARGS__, 32, ERR, 31, ERR, 30, ERR, 29, ERR, 28, ERR, 27, ERR, 26, ERR, 25, ERR, 24, ERR, 23, ERR, 22, ERR, 21, ERR, 20, ERR, 19, ERR, 18, ERR, 17, ERR, 16, ERR, 15, ERR, 14, ERR, 13, ERR, 12, ERR, 11, ERR, 10, ERR, 9, ERR, 8, ERR, 7, ERR, 6, ERR, 5, ERR, 4, ERR, 3, ERR, 2, ERR, 1, ERR)

#define ADAPT_DETAIL_SELECT_MACRO_NUM_PAIR(MACRO, CONV, ...) ADAPT_EXPAND_VARS(ADAPT_CONCAT, (MACRO, ADAPT_GET_NUM_ARGS_PAIR(__VA_ARGS__)))(CONV, __VA_ARGS__)


#define ADAPT_DETAIL_NUM_ARGS_TRIO_2( _1a,  _1b,  _1c,  _2a,  _2b,  _2c,  _3a,  _3b,  _3c,  _4a,  _4b,  _4c,  _5a,  _5b,  _5c,  _6a,  _6b,  _6c,  _7a,  _7b,  _7c,  _8a,  _8b,  _8c,\
									  _9a,  _9b,  _9c, _10a, _10b, _10c, _11a, _11b, _11c, _12a, _12b, _12c, _13a, _13b, _13c, _14a, _14b, _14c, _15a, _15b, _15c, _16a, _16b, _16c,\
									 _17a, _17b, _17c, _18a, _18b, _18c, _19a, _19b, _19c, _20a, _20b, _20c, _21a, _21b, _21c, _22a, _22b, _22c, _23a, _23b, _23c, _24a, _24b, _24c,\
									 _25a, _25b, _25c, _26a, _26b, _26c, _27a, _27b, _27c, _28a, _28b, _28c, _29a, _29b, _29c, _30a, _30b, _30c, _31a, _31b, _31c, _32a, _32b, _32c, N, ...) N
#define ADAPT_DETAIL_NUM_ARGS_TRIO_1(...) ADAPT_EXPAND_VARS(ADAPT_DETAIL_NUM_ARGS_TRIO_2, (__VA_ARGS__))
#define ADAPT_GET_NUM_ARGS_TRIO(...) ADAPT_DETAIL_NUM_ARGS_TRIO_1(__VA_ARGS__, 32, ERR, ERR, 31, ERR, ERR, 30, ERR, ERR, 29, ERR, ERR, 28, ERR, ERR, 27, ERR, ERR, 26, ERR, ERR, 25, ERR, ERR,\
																			   24, ERR, ERR, 23, ERR, ERR, 22, ERR, ERR, 21, ERR, ERR, 20, ERR, ERR, 19, ERR, ERR, 18, ERR, ERR, 17, ERR, ERR,\
																			   16, ERR, ERR, 15, ERR, ERR, 14, ERR, ERR, 13, ERR, ERR, 12, ERR, ERR, 11, ERR, ERR, 10, ERR, ERR,  9, ERR, ERR,\
																			    8, ERR, ERR,  7, ERR, ERR,  6, ERR, ERR,  5, ERR, ERR,  4, ERR, ERR,  3, ERR, ERR,  2, ERR, ERR,  1, ERR, ERR)

#define ADAPT_DETAIL_SELECT_MACRO_NUM_TRIO(MACRO, CONV, ...) ADAPT_EXPAND_VARS(ADAPT_CONCAT, (MACRO, ADAPT_GET_NUM_ARGS_TRIO(__VA_ARGS__)))(CONV, __VA_ARGS__)


//MSVCとclang/gccで記述統一ができなかった。
#ifdef _MSC_VER

//コンマ版
#define ADAPT_DETAIL_EXPAND_CONV_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_2(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_3(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_4(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_5(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_6(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_7(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_8(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_9(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_10(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_11(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_12(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_13(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_14(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_15(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_16(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_17(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_18(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_19(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_20(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_21(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_22(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_23(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_24(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_25(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_26(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_27(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_28(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_29(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_30(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_31(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_32(CONV, x, ...) CONV(x), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_31, (CONV, __VA_ARGS__))

//コンマ、2個ずつ
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_1(CONV, x, y) CONV(x, y)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_2(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_3(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_4(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_5(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_6(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_7(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_8(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_9(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_10(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_11(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_12(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_13(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_14(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_15(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_16(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_17(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_18(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_19(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_20(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_21(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_22(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_23(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_24(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_25(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_26(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_27(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_28(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_29(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_30(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_31(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_32(CONV, x, y, ...) CONV(x, y), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_PAIR_31, (CONV, __VA_ARGS__))

// コンマ、3個ずつ
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_1(CONV, x, y, z) CONV(x, y, z)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_2(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_3(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_4(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_5(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_6(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_7(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_8(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_9(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_10(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_11(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_12(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_13(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_14(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_15(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_16(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_17(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_18(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_19(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_20(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_21(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_22(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_23(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_24(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_25(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_26(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_27(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_28(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_29(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_30(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_31(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_32(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_TRIO_31, (CONV, __VA_ARGS__))



//セミコロン版
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30, (CONV, __VA_ARGS__))
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_32(CONV, x, ...) CONV(x); ADAPT_EXPAND_VARS(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31, (CONV, __VA_ARGS__))

#else

//コンマ版
#define ADAPT_DETAIL_EXPAND_CONV_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_2(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_3(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_4(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_5(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_6(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_7(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_8(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_9(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_10(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_11(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_12(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_13(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_14(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_15(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_16(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_17(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_18(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_19(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_20(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_21(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_22(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_23(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_24(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_25(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_26(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_27(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_28(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_29(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_30(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_31(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_32(CONV, x, ...) CONV(x), ADAPT_DETAIL_EXPAND_CONV_31(CONV, __VA_ARGS__)

//コンマ、2個ずつ
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_1(CONV, x, y) CONV(x, y)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_2(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_3(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_4(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_5(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_6(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_7(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_8(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_9(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_10(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_11(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_12(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_13(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_14(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_15(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_16(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_17(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_18(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_19(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_20(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_21(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_22(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_23(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_24(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_25(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_26(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_27(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_28(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_29(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_30(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_31(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_PAIR_32(CONV, x, y, ...) CONV(x, y), ADAPT_DETAIL_EXPAND_CONV_PAIR_31(CONV, __VA_ARGS__)

// コンマ、3個ずつ
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_1(CONV, x, y, z) CONV(x, y, z)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_2(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_3(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_4(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_5(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_6(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_7(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_8(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_9(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_10(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_11(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_12(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_13(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_14(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_15(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_16(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_17(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_18(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_19(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_20(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_21(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_22(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_23(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_24(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_25(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_26(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_27(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_28(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_29(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_30(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_31(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_TRIO_32(CONV, x, y, z, ...) CONV(x, y, z), ADAPT_DETAIL_EXPAND_CONV_TRIO_31(CONV, __VA_ARGS__)


//セミコロン版
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, x) CONV(x)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_1(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_2(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_3(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_4(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_5(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_6(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_7(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_8(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_9(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_10(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_11(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_12(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_13(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_14(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_15(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_16(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_17(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_18(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_19(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_20(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_21(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_22(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_23(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_24(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_25(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_26(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_27(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_28(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_29(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_30(CONV, __VA_ARGS__)
#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_32(CONV, x, ...) CONV(x); ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_31(CONV, __VA_ARGS__)

#endif


#define ADAPT_DETAIL_EXPAND_CONV(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM(ADAPT_DETAIL_EXPAND_CONV_, CONV, __VA_ARGS__)

#define ADAPT_DETAIL_EXPAND_CONV_PAIR(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM_PAIR(ADAPT_DETAIL_EXPAND_CONV_PAIR_, CONV, __VA_ARGS__)

#define ADAPT_DETAIL_EXPAND_CONV_TRIO(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM_TRIO(ADAPT_DETAIL_EXPAND_CONV_TRIO_, CONV, __VA_ARGS__)

#define ADAPT_DETAIL_EXPAND_CONV_SEMICOLON(CONV, ...) ADAPT_DETAIL_SELECT_MACRO_NUM(ADAPT_DETAIL_EXPAND_CONV_SEMICOLON_, CONV, __VA_ARGS__)




#endif