#include <format>
#include <iostream>
#include <vector>
#include <string>
#include <cassert>
#include <cmath>
#include <complex>
#include <ranges>
#ifdef ADAPT_IMPORT_MODULE
#include <OpenADAPT/Macros.h>
import adapt;
#else
#include <OpenADAPT/ADAPT.h>
#endif

#ifdef ADAPT_ENABLE_PREBUILT_PARSER
#include <OpenADAPT/Parser.h>
#endif

using namespace adapt::lit;

adapt::DTree MakeDTree();
void StoreData(adapt::DTree& usa);

void QuickstartParser()
{
#ifdef ADAPT_ENABLE_PREBUILT_PARSER
	std::cout << "[[Quickstart Parser]]" << std::endl;

	adapt::DTree usa = MakeDTree();
	StoreData(usa);

	using Lambda = adapt::eval::RttiFuncNode<adapt::DTree>;

	// This example demonstrates how to make lambda functions by parsing string expressions.
	// Before reading this example, please read the "quickstart_dtree.cpp"/"quickstart_dtable.cpp"
	// to understand what lambda functions are and how to use them.

	// The main function of the parser, adapt::Parse, is declared in OpenADAPT/Parser.h, and its implementation is in OpenADAPT/Parser_impl.h.
	// However, it is not recommended to include OpenADAPT/Parser_impl.h directly,
	// because it contains very large code generated by macros for parsing various expressions and may cause long compilation time.
	// It is also not recommended to use adapt::Parse with STree/STable/SHist for the same reason.
	// Instead, you can pre-compile static/shared libraries that include the implementation of the parser for DTree/DTable/DHist
	// by passing -DENABLE_PREBUILT_PARSER to CMake when building OpenADAPT, and then link OpenADAPT::Parser to your project.


	// The parser can recognize the field names defined in the hierarchical structure of the container,
	// and can also recognize the same operators and functions as the non-string lambda functions.
	// However, there are some differences between the string expressions and non-string expressions:
	// 1. functions as a method of containers (e.g. usa.pos(1), usa.size(2_layer)) can be used without the container name (e.g. pos(1), size(2)).
	// 2. integer/floating-point literals are treated as I32/F64 by default, and a suffix can be added to specify the type (e.g. 1000i64, 100.0f32).
	// 3. currently user-defined functions cannot be used in string expressions.

	Lambda population_density = adapt::Parse(usa, "population / area");
	// The above code generates completely the same lambda function as the following code:
	// ADAPT_GET_PLACEHOLDERS(usa, population, area);
	// Lambda population_density = population / area;
	assert(population_density.GetLayer() == 2_layer && population_density.GetType() == adapt::FieldType::F64);
	adapt::Bpos baytown_index = { 1, 0, 2 };
	std::cout << population_density(usa, baytown_index).f64() << std::endl;// 83701 / 32.7 = 2559.6

	Lambda average_population_density_of_cities_with_large_area = adapt::Parse(usa, "mean_if(population / area, area > 100.0)");
	assert(average_population_density_of_cities_with_large_area.GetLayer() == 1_layer && average_population_density_of_cities_with_large_area.GetType() == adapt::FieldType::F64);
	adapt::Bpos harris_index = { 1, 0 };
	std::cout << average_population_density_of_cities_with_large_area(usa, harris_index).f64() << std::endl;// (2304580/1500.7 + 151950/114.4) / 2 = 1431.95

	auto average_population_density = adapt::Parse(usa, "tostr(mean3(population / area) * 2.589988) + \"(/mi^2)\"");
	std::cout << average_population_density(usa).str() << std::endl;// 5362.28(/mi^2).

	std::cout << std::endl;
#endif
}